#스페이스 규칙 잘지켜야한다.
server:
  port: 7979
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://49.247.193.222:3306/starbucks?serverTimezone=Asia/Seoul&characterEncoding=utf8

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rkdmfdl0070
    
#파일업로드  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true 

# 시큐리티 사용자 기본 아이디 비번 디폴트 세팅      
#  security:
#    user:
#      name: test
#      password: 1234

#파일 저장할 경로 git pull할때마다 자기주소로 바꿔야 에러안남
file:
  path: E:\git\springboot-mybatis-starbucks\src\main\resources\static\images
          

